### ISSUE TITLE
Sending and Receiving Data?

### ISSUE THREAD

**Issue by gridfriday** [Skyost/Bonsoir#5]
**Describe the bug**
I don't see any way to exchange data between the broadcaster and the discoverer.

I can successfully set up a broadcaster and a discoverer, but after the initial handshake, I can find no functions or methods that allow the passage of data.

What am I missing?

**Comment by Skyost** [comment]
Bonsoir is just here for the discovery and for the broadcast. It's your role to setup the data exchange (as it's not something like a web server or an udp server). As an example, here's how I will use it in my game :

**Party host :**

* Start-up a WebSocket Server instance on port 1234 (for instance).
* Run a Bonsoir Broadcast for the service : `{name: "Tommy's party", type: "_skyost-game._tcp", port: 1234}`.

**Party client :**

* Run a Bonsoir Discovery for the type `_skyost-game._tcp`. If the client's device is connected to the same network than the host's device, then it should detect the broadcasted service.
* Once selected by the user, I close the Discovery.
* Now we can establish the connection to the WebSocket Server via a WebSocket Client (since we know which IP address and which port to use).

Then, once the party host is ready to launch the party, we can stop the Bonsoir Broadcast.

**Comment by Alvish0407** [comment]
no able to connect to the websocket
<img width="400" alt="Screenshot 2024-10-19 at 7 00 05 PM" src="https://github.com/user-attachments/assets/acb01f55-04ea-46ad-8918-e6b444f10093">
<img width="1489" alt="Screenshot 2024-10-19 at 7 00 05 PM" src="https://github.com/user-attachments/assets/92216899-a29d-4831-a75a-5b7518b33269">

**Comment by Alvish0407** [comment]
So, i figured it out. We have to open `ServerSocket` from **Host** and `Socket` from the **client**.

[Reference](https://github.com/alexrintt/ttt/blob/8f2eef4e3bf0a3b12cc394298e1bb817da73325b/lib/pages/create_room_page.dart#L63)
